jobs: 100
cluster: "sbatch --account berglandlab -p standard -o {resources.log_dir}/{rule}.%A.out -e {resources.log_dir}/{rule}.%A.err -J {rule} --ntasks-per-node={resources.ntasks_per_node} -N 1 -t {resources.time_limit} --mem {resources.memory_limit}G"
default-resources: [ntasks_per_node=1, memory_limit=10, time_limit=120]
